config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  concern :commentable do
    resources :comments
  end

  resources :users
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :comment, presence: true 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :comments, as: :commentable

  validates :title, :article, :author_id, presence: true
  validates :title, length: {in: 1..20}
  validates :article, length: {in: 1..10000}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, class_name: 'Post', foreign_key: 'author_id'
  has_many :comments, as: :commentable

  validates :name, :email, :password, presence: true
  validates :bio, length: {maximum: 500}
  validates :location, length: {maximum: 20}
  validates :password, length: {in: 8..20}
  has_secure_password
  validate :valid_email

  def valid_email
    if !email.match(/\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/)
      errors.add(:email, 'Email is not valid')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    require_user
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    require_user
    @comment = Comment.find(params[:id])
  end

  def update
    require_user
    @post = Post.find([params[:post_id]])
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    require_user
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_comments_path
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    require_user
    @post = Post.new
  end

  def create
    require_user
    @post = current_user.articles.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new()
  end

  def edit
    require_user
    @post = Post.find(params[:id])
  end

  def update
    require_user
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    require_user
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :article)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    require_user
    @user = User.find(params[:id])
  end

  def update
    require_user
    @user = User.find(params[:id])

    if @user.update
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    require_user
    @user = User.find(params[:id])
    @user.destroy

    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :location, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def login(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    redirect_to new_user_path unless logged_in?
  end

end

app/views/comments/_comment.html.erb
<div class="comments">

  <p><%= comment.user.name %></p>
  <p><%= comment.comment %></p>
  <p><%= time_ago_in_words(comment.created_at) %></p>

  <% if current_user == comment.user %>
    <span><%= link_to 'Edit', edit_post_comment_path(@post) %></span>
    <span><%= link_to 'Delete', post_comment_path(comment), method: 'delete' %></span>
  <% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
  <%= f.label :comment %>
  <%= f.text_area :comment %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<div class="edit-comment">

  <%= form_for @comment, url: post_comment_path(@comment) do |f| %>
    <%= f.label :comment %>
    <%= f.text_area :comment, rows: "10", cols: "70" %>
    <%= f.submit %>
  <% end %>

</div>

app/views/comments/show.html.erb
<%= comment.user %>
<%= comment.comment %>

<% if current_user == comment.author %>
  <%= link_to 'Edit', edit_comment_path(comment) %>
  <%= link_to 'Delete', comment_path(comment), method: 'delete' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Dosis|Raleway" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header>
  <%= link_to 'Home', root_path %>
  <%= link_to 'Users', users_path %>
  <% if logged_in? %>
    <%= link_to 'Profile', current_user %>
    <%= link_to 'Logout', logout_path, method: 'delete' %>
    <%= link_to 'New article', new_post_path %>
  <% else %>
    <%= link_to 'Sign up', new_user_path %>
    <%= link_to 'Log in', login_path %>
  <% end %>
</header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-container">

  <div class="error-container">
    <% if @post.errors.any? %>
      <%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:
      <% @post.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
    <% end %>
  </div>

  <div class="form-container">
    <%= form_for @post do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :article %>
      <%= f.text_area :article, cols: "100", rows: "40" %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<section class="posts-container">
  <% @posts.each do |post| %>
    <article class="post-container">
      <p><%= link_to post.title, post_path(post.id) %></p>
      <p><%= link_to post.author.name, user_path(post.author.id) %></p>
    </article>
  <% end %>
</section>

app/views/posts/show.html.erb
<div class="article-container">

  <h1><%= @post.title %></h1>
  <p><%= @post.article %></p>

  <% if current_user == @post.author %>
    <%= link_to 'Edit', edit_post_path(@post) %>
    <%= link_to 'Delete', post_path(@post), method: 'delete' %>
  <% end %>


  <% if logged_in? %>
    <h2>New Comment</h2>
    <%= render 'comments/form' %>
  <% else %>
    <h2><%= link_to 'Login', new_user_path %> to leave a new comment</h2>
  <% end %>

<div class="comments-container">
  <%= render @post.comments %>
</div>

</div>

app/views/users/_form.html.erb
<div class="user-form-container">

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prohibited
    this user from being saved:
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  <% end %>

  <div class="user-form">
    <%= form_for @user do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.email_field :email %>
      <%= f.label :location %>
      <%= f.text_field :location %>
      <%= f.label :bio %>
      <%= f.text_area :bio, rows: '10' %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.submit %>
    <% end %>
  </div>

</div>

app/views/users/index.html.erb
<div class="users-container">

<% @users.each do |user| %>
<div class="user-container">
    <h3><%= link_to user.name, user_path(user.id) %></h3>
    <p><%= pluralize(user.articles.count, 'post') %></p>
    <p>Member for <%= time_ago_in_words(user.created_at) %></p>
</div>
<% end %>

</div>

app/views/users/show.html.erb
<div class="user-container user-show">
  <h1><%= @user.name %></h1>
  <p><%= @user.location.empty? ? 'Someplace' : @user.location %></p>
  <p>Member for <%= time_ago_in_words(@user.created_at) %></p>
</div>

<div class="user-container user-show about-me">
  <p>About me:</p>
  <p><%= @user.bio.empty? ? "This user hasn't entered a bio yet." : @user.bio %></p>
</div>

<%= link_to 'Edit profile', edit_user_path if current_user == @user %>